version: '3.8'

services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-taq_u_app}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-taq_u_app}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/taq_u_app?schema=public}
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
      PRISMA_GENERATE_DATAPROXY: ${PRISMA_GENERATE_DATAPROXY:-true}
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    command: sh -c "pnpm run setup"
    restart: unless-stopped

volumes:
  postgres_data:
