version: "3.8"
services:
  db:
    image: postgres:16.3
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: sh -c "pnpm run setup"

volumes:
  postgres_data:
